"""init

Revision ID: aa2f828b847a
Revises: 
Create Date: 2023-12-06 18:34:06.753933

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from src.database import types
from src.gorzdrav_api import schemas

# revision identifiers, used by Alembic.
revision: str = "aa2f828b847a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking',
                    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
                    sa.Column("time_ranges", sa.ARRAY(sa.Integer()), nullable=False),
                    sa.Column("district",
                              types.PydanticType(schemas.District),
                              nullable=False),
                    sa.Column("clinic",
                              types.PydanticType(schemas.Clinic),
                              nullable=False),
                    sa.Column("speciality",
                              types.PydanticType(schemas.Speciality),
                              nullable=False),
                    sa.Column("doctor",
                              types.PydanticType(schemas.Doctor),
                              nullable=False),
                    sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking"))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tracking")
    # ### end Alembic commands ###
